language: csharp
mono: none
dotnet: 3.1.402 # to update this value in the future, try `dotnet --list-sdks` as a start

install:
- dotnet restore

script:
- dotnet build RomanizationNet.sln --configuration Release --no-restore
- dotnet test RomanizationTests/RomanizationTests.csproj

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && bash ./deploy.sh $NUGET_API_KEY $NUGET_SOURCE $GH_PACKAGES_API_KEY $GH_PACKAGES_SOURCE
  on:
    branch: main
