language: csharp
mono: none
dotnet: 3.1.402 # to update this value in the future, try `dotnet --list-sdks` as a start

install:
 - dotnet restore

 script:
 - dotnet build
 - dotnet test RomanizationTests/RomanizationTests.csproj